exclude:
  - calmap
language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "3.5"
    - python: "2.7"
    - python: "nightly"
# command to install dependencies
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pillow
# command to run tests
script: 
  - pytest --cov=./
after_success:
  - codecov
