name: atcprocessor
channels:
  - conda-forge
  - https://conda.anaconda.org/rnelsonchem
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/snorfalorpagus
  - defaults
dependencies:
  - matplotlib=2.2.2
  - pandas=0.23.1
  - python=3.6.6
  - seaborn=0.9.0

